// <auto-generated />
using System;
using Controle_Escolar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Controle_Escolar.Migrations
{
    [DbContext(typeof(BancoContext))]
    partial class BancoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Controle_Escolar.Models.AtividadeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("TurmaModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TurmaModelId");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("Controle_Escolar.Models.ProfModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomeProf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Controle_Escolar.Models.TurmaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfessorId");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("Controle_Escolar.Models.AtividadeModel", b =>
                {
                    b.HasOne("Controle_Escolar.Models.TurmaModel", null)
                        .WithMany("ListaAtv")
                        .HasForeignKey("TurmaModelId");
                });

            modelBuilder.Entity("Controle_Escolar.Models.TurmaModel", b =>
                {
                    b.HasOne("Controle_Escolar.Models.ProfModel", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("Controle_Escolar.Models.TurmaModel", b =>
                {
                    b.Navigation("ListaAtv");
                });
#pragma warning restore 612, 618
        }
    }
}
